Repository open-cluster-management-io/config-policy-controller, pull requests merged in 2021-07, with the labels that each got.

#1 add default value for CONTROLLER_NAMESPACE
  Makefile
Labels: approved, lgtm

#2 fix make test-dependencies by only perform 'mv' if kubebuilder doesn't exist already
  Makefile
Labels: approved, lgtm

#3 Fix the deploy make target
  Makefile
  deploy/crds/policy.open-cluster-management.io_v1alpha1_configurationpolicy_cr.yaml
Labels: approved, lgtm

#4 Remove linting target
  Makefile
  README.md
Labels: approved

#5 Download the build harness bootstrap Makefile only when it's not present
  Makefile
Labels: approved, lgtm

#6 Update readme
  README.md
  SECURITY.md
Labels: approved, dco-signoff: yes, lgtm

#8 fix GOBIN path issue
  Makefile
Labels: dco-signoff: yes

#9 improve e2e test process doc
  README.md
Labels: approved, dco-signoff: yes, lgtm

#10 Update README
  README.md
Labels: approved, dco-signoff: yes, lgtm
