Repository open-cluster-management-io/config-policy-controller, pull requests merged in 2023-03, with the labels that each got.

#108 Make config policies with no objects compliant
  controllers/configurationpolicy_controller.go
  test/e2e/case30_multiline_templatization_test.go
  test/resources/case30_multiline_templatization/case30_no_object.yaml
Labels: enhancement, lgtm, approved, dco-signoff: yes

#107 Fix status for invalid object
  controllers/configurationpolicy_controller.go
  test/e2e/case23_invalid_field_test.go
Labels: lgtm, approved, dco-signoff: yes

#110 Sync the common Makefile
  .copyrightignore
  Makefile
  build/common/Makefile.common.mk
  build/common/config/.golangci.yml
  build/common/scripts/config_docker.sh
  build/common/scripts/install-operator-sdk.sh
  build/common/scripts/lint_copyright_banner.sh
  controllers/configurationpolicy_controller.go
  docs/adoption_guide.md
  docs/development.md
Labels: lgtm, approved, dco-signoff: yes

#112 Fix order of events on create or delete
  Makefile
  controllers/configurationpolicy_controller.go
  test/e2e/case15_event_format_test.go
Labels: lgtm, approved, dco-signoff: yes

#113 Fix compliance state on missing obj evt
  controllers/configurationpolicy_controller.go
Labels: lgtm, approved, dco-signoff: yes

#111 Pod history toggling issue
  controllers/configurationpolicy_controller_test.go
  controllers/configurationpolicy_utils.go
  controllers/configurationpolicy_utils_test.go
  policy-security.yml
  test/e2e/case12_list_compare_test.go
  test/e2e/case20_delete_objects_test.go
  test/e2e/case25_related_object_metric_test.go
  test/e2e/case26_user_error_metric_test.go
  test/e2e/case28_evauluation_metric_test.go
  test/e2e/case31_policy_history_test.go
  test/e2e/case8_status_check_test.go
  test/resources/case31_policy_history/pod-config-policy-number.yaml
  test/resources/case31_policy_history/pod-config-policy.yaml
  test/resources/case31_policy_history/pod-policy-number.yaml
  test/resources/case31_policy_history/pod-policy.yaml
Labels: lgtm, approved, dco-signoff: yes, do-not-merge/hold
